# Basics of Python Part 02

## Operators

### Arithmetic Operators

In [1]:

print(2+3)    # addition
print(2-3)    # subtraction
print(2*3)    # multiplication
print(2/3)    # float division
print(2//3)   # integer division
print(2%3)    # modulus or remainder
print(2**3)   # raise to power (here 2 raise to power 3)


5
-1
6
0.6666666666666666
0
2
8



### Assignment Operators

In [2]:

# assign value of right to left ( = operator )

y = 5   # value 5 assigned to variable y
print(y)

a,b = 5,6  # two values assigned in single line
print(a,b)


5
5 6



### Relational Operators

In [3]:

# return a bool value (either true or false after evaluating the expression)

print(2<3)    # less than
print(2<=3)   # less than equal to
print(2>3)    # greater than
print(2>=3)   # greater than equal to
print(2==3)   # equal to
print(2!=3)   # not equal to


True
True
False
False
False
True



### Logical Operators

In [4]:

a = 5
b = 4

print(a<4 and b<5)

        # for 'and' -
        # True + True = True 
        # T + F = F
        # F + T = F
        # F + F = F

print(a>4 or b<3)

        # for 'or' -
        # True + True = True 
        # T + F = T
        # F + T = T
        # F + F = F

x = True
print(not x) 
        # not --> reverse 
        # for 'not' -
        # True -> False 
        # False -> True


False
True
False


### Unary Operators

In [5]:

# ( - operator negates the sign )
n = 7
print(-n)

n = -7
print(-n)


-7
7



### Bitwise Operators

In [6]:

x = 5
y = 8

# Returns x with the bits shifted to the left by y places (and new bits on the right-hand-side are zeros). 
# This is the same as multiplying x by 2 ** y ( 2 raise to power y) .
print("left shift",x<<y)

# Returns x with the bits shifted to the right by y places. This is the same as integer dividing x by (2 ** y).
print("right shift",x >> y)

# Does a "bitwise and". Each bit of the output is 1 if the corresponding bit of x AND of y is 1, otherwise it's 0.
print("bitwise and",x & y)

# Does a "bitwise or". Each bit of the output is 0 if the corresponding bit of x AND of y is 0, otherwise it's 1.
print("bitwise or",x | y)

# Returns the complement of x - the number you get by switching each 1 for a 0 and each 0 for a 1. 
# This is the same as -x - 1 (complement of x - 1).
print("complement of x",~x)

# Does a "bitwise exclusive or". Each bit of the output is the same as the corresponding bit in x if that bit in y is 0, 
# and it's the complement of the bit in x if that bit in y is 1.
print("bitwise exclusive or (xor)",x^y)



left shift 1280
right shift 0
bitwise and 0
bitwise or 13
complement of x -6
bitwise exclusive or (xor) 13



# Number System

In [7]:

# decimal to binary

x = bin(25)
print(x)
print(type(x))

# octal to binary
x = bin(0o31)
print(x)
print(type(x))

# hexadecimal to binary
x = bin(0x31)
print(x)
print(type(x))



0b11001
<class 'str'>
0b11001
<class 'str'>
0b110001
<class 'str'>


In [8]:

# binary to decimal
# 0b denotes binary 

print(0b11001)

# octal to decimal
# 0o denotes octal 

print(0o31)

# hexadecimal to decimal
# 0x denotes hexadecimal 

print(0x31)



25
25
49


In [9]:

# binary to octal

x = oct(0b11001)
print(x)

# decimal to octal

x = oct(25)
print(x)

# hexadecimal to octal

x = oct(0x31)
print(x)


0o31
0o31
0o61


In [10]:

# binary to hexadecimal

x = hex(0b11001)
print(x)

# octal to hexadecimal

x = hex(0o31)
print(x)

# decimal to hexadecimal

x = hex(25)
print(x)

0x19
0x19
0x19


## Aliasing

In [11]:

# importing math library

import math
print(math.sqrt(5))  # printing square root of 5


2.23606797749979


In [12]:

import math as m        # as used for aliasing

print(m.sqrt(4))           # because of aliasing math can be represented as m


2.0



## Math Library

In [13]:

import math as m        # as used for aliasing

# square root
print(m.sqrt(4))

# power(x,y) x raise to power y
print(m.pow(4,2))

# floor
print(m.floor(4.6))

# ceil
print(m.ceil(4.6))

# value of pi
print(m.pi)

# value of e
print(m.e)


2.0
16.0
4
5
3.141592653589793
2.718281828459045



## User Input

In [14]:

x = input("enter value : ")  # for taking input from user
print(x)
print(type(x))               # input() function gives input in string format always


enter value :  5


5
<class 'str'>


In [15]:

# typecast it to integer
x = int(input("enter value : "))
print(x)
print(type(x))

y = x + 5
print(y)


enter value :  5


5
<class 'int'>
10


In [16]:

# eval() to evaluate an expression 
x = eval(input("enter expression : "))
print(x)
print(type(x))


enter expression :  2+5-6


1
<class 'int'>


## Conditional statements

### If :

In [17]:

if True:
    print("inside the if")

if(3<5):
    print("3 less than 5")
    

inside the if
3 less than 5



### If - Else :

In [18]:

if False:
    print("inside the if")
else:
    print("inside the else")


if(3>5):
    print("3 greater than 5")
else:
    print("3 less than 5")
    

inside the else
3 less than 5



### if - Elif - else :

In [19]:

if False:
    print("inside the if")
elif True:
    print("inside the elif")
else:
    print("inside the else")


if(3>5):
    print("3 greater than 5")
elif(3<4):
    print("3 less than 4")
else:
    print("inside else")
    

inside the elif
3 less than 4


In [20]:

if False:
    print("inside the if")
elif False:
    print("inside the elif")
else:
    print("inside the else")


if(3>5):
    print("3 greater than 5")
elif(3>6):
    print("3 greater than 6")
else:
    print("inside else")


inside the else
inside else


## Loops

### While Loop

In [21]:

i = 0
while(i<5):
    print(i,end=" ")   # end=" " for printing in same line, on the new line is not printed
    i+=1


0 1 2 3 4 


### For Loop

In [22]:

for i in range(0,5):
    print(i,end=" ")
    

0 1 2 3 4 

## Break

In [23]:

for i in range(0,5):
    if(i==2):
        break              # break terminates the loop (here when the condition is met, when i is 2
    print(i,end=" ")
    

0 1 


## Continue

In [24]:

for i in range(0,5):
    if(i==2):
        continue              # continue skips the loop iteration when the condition is met, here when i is 2
    print(i,end=" ")
    

0 1 3 4 

## Pass

In [25]:

for i in range(0,5):
    if(i==3):
        pass                 # pass represents when nothing is to write, can't assign empty
    else:
        print(i)
    

0
1
2
4


## Numpy array

In [26]:
pip install numpy


[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.0.10/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [27]:

# numpy array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [28]:
print(arr.size)   # no. of elements in array

5


In [29]:
print(arr.ndim)  # dimension of array

1


In [30]:

arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]])

print(arr.shape)  # rows and columns of array

(2, 5)


In [35]:
from numpy import *

arr = array([1,2,3,4,5])
print(sum(arr))        # sum of all elements of array

print(log(arr))        # log of all elements of array individually

print(sqrt(arr))       # square root of all elements of array individually

print(min(arr))        # minimum among all elements of array

print(max(arr))        # maximum among all elements of array


15
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.41421356 1.73205081 2.         2.23606798]
1
5


In [36]:

arr1 = np.array([1,2,3,4,5])

arr2 = np.array([6,7,8,9,10])

print(concatenate([arr1,arr2]))   # concatenation of array 1 and array 2

[ 1  2  3  4  5  6  7  8  9 10]


#### 2D/ Multidimensional array using Numpy

In [37]:

# 2-D array 

arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]])

print(arr)

print(arr.shape)
print(arr.ndim)
print(arr.size)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2
10


In [38]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]])

print(arr.flatten())    # n - dimensional array to 1-D array


[ 1  2  3  4  5  6  7  8  9 10]


In [39]:

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.reshape(5,2))         # converts into array of 5 rows and 2 columns


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [42]:

arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]])

# convert array to matrix (to access multiple functionalities of matrices)
arr1 = matrix(arr)

# or

arr2 = matrix("1 2 3 4 5; 10 9 8 7 6")

# printing matrix
print("matrix arr1 : \n\n",arr1)
print("\n matrix arr2 : \n\n",arr2)


matrix arr1 : 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 matrix arr2 : 

 [[ 1  2  3  4  5]
 [10  9  8  7  6]]


In [43]:

# addition of matrices

print(" addition of matrices : \n\n",arr1 + arr2)

# subtraction of matrices

print("\n\n subtraction of matrices : \n\n",arr1 - arr2)



 addition of matrices : 

 [[ 2  4  6  8 10]
 [16 16 16 16 16]]


 subtraction of matrices : 

 [[ 0  0  0  0  0]
 [-4 -2  0  2  4]]


In [44]:

arr1 = matrix("1 2 3; 10 9 8")
arr2 = matrix("1 2 7 4 5; 1 9 8 7 6; 1 4 6 8 2")

# multiplication of matrices

print("multiplication of matrices : \n\n",arr1 * arr2)

multiplication of matrices : 

 [[  6  32  41  42  23]
 [ 27 133 190 167 120]]


In [45]:


arr2 = matrix("1 2 7 4 5; 1 9 8 7 6; 1 4 6 8 2")

# diagonal of matrix
print(diagonal(arr2))

# minimum element in matrix
print(arr2.min())

# maximum element in matrix
print(arr2.max())

# transpose of matrix
print(transpose(arr2))


[1 9 6]
1
9
[[1 1 1]
 [2 9 4]
 [7 8 6]
 [4 7 8]
 [5 6 2]]



## Copying Array 

### Shallow Copy

In [46]:

arr1 = np.array([1,2,3,4,5])
arr2 = arr1.view()               # shallow copy
print(arr2)
print(id(arr1))
print(id(arr2))

# it is shallow copy as arr2 is copy of arr1 but both are still 'dependent' on each other
arr1[2]=10

print("arr1 :",arr1)         # value changed in arr1
print("arr2 :",arr2)         # but point to notice, value changed in arr2 as well
print(id(arr1))
print(id(arr2))



[1 2 3 4 5]
4647921840
4567883600
arr1 : [ 1  2 10  4  5]
arr2 : [ 1  2 10  4  5]
4647921840
4567883600


### Deep Copy

In [47]:

arr1 = np.array([1,2,3,4,5])
arr2 = arr1.copy()               # deep copy
print(arr2)
print(id(arr1))
print(id(arr2))

# it is deep copy as arr2 is copy of arr1 and both are 'independent' on each other
arr1[2]=10

print("arr1 :",arr1)         # value changed in arr1
print("arr2 :",arr2)         # but point to notice, value not changed in arr2
print(id(arr1))
print(id(arr2))

[1 2 3 4 5]
4647920304
4647918864
arr1 : [ 1  2 10  4  5]
arr2 : [1 2 3 4 5]
4647920304
4647918864


## Functions

In [48]:

# function definition

def greet():                # keyword 'def'
    print("hello world")

# calling function greet
greet()

hello world


In [49]:

# function returning something (can return anything set, dictionary, list and so on... )

def add(x,y):
    return x + y

returned_value = add(5,3)
print(returned_value)


8


In [50]:
def add(x,y):
    pass            # empty function

add(5,3)

In [51]:
# function returning multiple values

def add_sub(x,y):
    return x+y, x-y

returned_value1, returned_value2 = add_sub(5,3)
print(returned_value1,returned_value2)


8 2


### Types of arguments

- Formal Arguments
- Actual Arguments

In [52]:

def add(x,y):               # ( in definition of function, parameters/arguments x and y are formal arguments )
    return x + y

returned_value = add(5,3)   # ( in calling of function, parameters/arguments passed, here 5 and 3, are actual arguments )
print(returned_value)


8


### Types of actual arguments

- Position
- Keyword
- Default
- Variable length
- Keyworded variable length

### 1. Position

In [53]:


def person(name,age):
    print(name)
    print(age-5)

person('devanshee',20)     #  actual arguments

# arguments assigned as per position 1st element to 1st one (i.e. devanshee --> name) and 2nd one with 2nd (i.e. 20 --> age)
# if position of actual arguments changed, it will give error as devanshee will be assigned to age,
# and age-5 can't be done as age is a string now.


devanshee
15


### 2. Keyword

In [54]:

# Keyword  (can be used to avoid above problem of passing arguments at their postion only)

def person(name,age):
    print(name)
    print(age-5)

person(age = 20, name = 'devanshee')     #  actual arguments

# arguments assigned as per keywords 'age' element to age (i.e. 20 --> age) and 'name' element with name (i.e. devanshee --> name)
# if position of actual arguments changed, it will not give error.



devanshee
15


### 3. Default

In [55]:


def person(name,age = 10):
    print(name)
    print(age)

person('devanshee')     #  actual arguments

# arguments assigned as per position 1st element to 1st one (i.e. devanshee --> name) and age is not passed.
# it won't cause error because default value is passed to age (default value to be used in case of not specifically provided) 



devanshee
10


### 4. Variable length

In [56]:


def fun(a, *b):      # only 2 formal arguments
    print("a: ",a) 
    print("b: ",b)

fun(2,3,4,5,6,7)     #  variable length actual arguments
fun(2,3,4,5)

# arguments assigned as per position 1st element to 1st one (i.e. 2 --> a) and rest all is assigned to b in form of tuple.


a:  2
b:  (3, 4, 5, 6, 7)
a:  2
b:  (3, 4, 5)


### 5. Keyworded Variable length arguments ( **kwargs )

In [57]:


def fun(name, **dict):      # only 2 formal arguments
    print("name: ",name) 
    print("dict: ",dict)

fun('devanshee',age=20,weight=42)        #  variable length actual arguments along with keywords

# arguments assigned as per position 1st element to 1st one (i.e. 'devanshee' --> name) and
# rest all is assigned to b in form of dictionary (key-value pair).

# another example -
fun('deveshi',age=21)


name:  devanshee
dict:  {'age': 20, 'weight': 42}
name:  deveshi
dict:  {'age': 21}
